namespace AikaEmu.GameServer.Models.Units.Npc.Const
{
    public enum DialogType : uint
    {
        Talk = 1,
        Quest = 2,
        Teleport = 3,
        MoveToWar = 4,
        Store = 5,
        StoreSkill = 6,
        Bank = 7,
        ChatClose = 8,
        RegisterWar = 9,
        GuildCreate = 10,
        GuildBank = 11,
        DialogEnd = 12,
        PranStation = 13,
        Craft = 15,
        Fortification = 16,
        Enchant = 17,
        Transfer = 18,
        LevelDown = 19,
        ChangeNation = 20,
        QuestMenu = 21,
        QuestAccept = 22,
        QuestReward = 24,
        SaveLocation = 25,
        EnterInstance = 26,
        Repair = 31,
        RepairAll = 32,
        Dismantle = 33,
        BlessFree = 35,
        BattleField = 37,
        Upgrade = 39,
        QuestReward2 = 40,
        NationStatus = 41,
        GuildSkills = 46,
        PranCostumeEnchant = 62,
        TeleportDisckeroa = 63,
        BlessPaid = 65,
        Evolution = 71,
        StoneRefinement = 74,
        StoneEnchant = 75,
        StoneCombination = 76,
    }
}