namespace AikaEmu.GameServer.Models.Char
{
    public enum CharFace : ushort
    {
        WarriorFace1 = 10,
        WarriorFace2 = 11,
        WarriorFace3 = 12,
        WarriorFace4 = 13,
        WarriorFace5 = 14,
        PaladinFace1 = 20,
        PaladinFace2 = 21,
        PaladinFace3 = 22,
        PaladinFace4 = 23,
        PaladinFace5 = 24,
        RiflemanFace1 = 30,
        RiflemanFace2 = 31,
        RiflemanFace3 = 32,
        RiflemanFace4 = 33,
        RiflemanFace5 = 34,
        DualGunnerFace1 = 40,
        DualGunnerFace2 = 41,
        DualGunnerFace3 = 42,
        DualGunnerFace4 = 43,
        DualGunnerFace15 = 44,
        WarlockFace1 = 50,
        WarlockFace2 = 51,
        WarlockFace3 = 52,
        WarlockFace4 = 53,
        WarlockFace5 = 54,
        ClericFace1 = 60,
        ClericFace2 = 61,
        ClericFace3 = 62,
        ClericFace4 = 63,
        ClericFace5 = 64,
    }
}